version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase
    commit-message:
      prefix: fix
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    commit-message:
      prefix: chore
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    commit-message:
      prefix: fix
    directories:
      - "/docker-dev"
    schedule:
      interval: weekly
