ARG TARGETPLATFORM

# Need to use Alpine 3.18.4 which uses Node 18 for arm/v6 and arm/v7, otherwise the build hangs.
# See https://github.com/nodejs/docker-node/issues/2077
FROM alpine:3.18.4 AS linux-arm-alpine
FROM alpine:3.21 AS linux-arm64-alpine
FROM alpine:3.21 AS linux-amd64-alpine
FROM alpine:3.21 AS linux-riscv64-alpine
FROM alpine:3.21 AS linux-386-alpine

FROM linux-${TARGETARCH}-alpine AS base

ENV NODE_ENV=development
WORKDIR /app

RUN apk add --no-cache tzdata eudev nodejs npm git

COPY . ./

ARG DATE
ARG VERSION
LABEL org.opencontainers.image.authors="Nerivec"
LABEL org.opencontainers.image.title="ZigBee on Host - Dev"
LABEL org.opencontainers.image.description="Open Source ZigBee stack designed to run on a host and communicate with a radio co-processor (RCP)"
LABEL org.opencontainers.image.url="https://github.com/Nerivec/zigbee-on-host"
LABEL org.opencontainers.image.documentation="https://github.com/Nerivec/zigbee-on-host"
LABEL org.opencontainers.image.source="https://github.com/Nerivec/zigbee-on-host"
LABEL org.opencontainers.image.licenses="GPL-3.0-or-later"
LABEL org.opencontainers.image.created=${DATE}
LABEL org.opencontainers.image.version=${VERSION}

ENTRYPOINT ["tail", "-f", "/dev/null"]
