name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches-ignore: [built-main]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Check
        run: npm run check:ci

      - name: Bench
        uses: CodSpeedHQ/action@v3
        with:
          run: npm run bench
          token: ${{ secrets.CODSPEED_TOKEN }}

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20, 22, 24]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Test
        run: npm run test:cov
